### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YaNIND** [edwinyoo44/libIPGeolocation#1]
this is WDPE support?

**Comment by edwinyoo44** [comment]
Is this?
https://github.com/edwinyoo44/libIPGeolocation/commit/5797bd60b268c3e5c88035b990b954767b236e8b

**Comment by YaNIND** [comment]
can i get an example? like example code

**Comment by edwinyoo44** [comment]
> can i get an example? like example code

See here
https://github.com/edwinyoo44/ProxyChecker
